export const brandOptions = [
    "Toyota",
    "BMW",
    "Honda",
    "Ford",
    "Chevrolet",
    "Nissan",
    "Volkswagen",
    "Hyundai",
    "Kia",
    "Mazda",
    "Mercedes-Benz",
    "Audi",
    "Renault",
    "Peugeot",
    "Fiat",
    "Otro",
  ];

export const mexicoCities = [
  "Ciudad de México",
  "Guadalajara",
  "Monterrey",
  "Puebla",
  "Toluca",
  "Tijuana",
  "León",
  "Querétaro",
  "Mérida",
  "San Luis Potosí",
  "Aguascalientes",
  "Cancún",
  "Chihuahua",
  "Saltillo",
  "Morelia",
  "Culiacán",
  "Hermosillo",
  "Veracruz",
  "Acapulco",
  "Cuernavaca",
  "Villahermosa",
  "Oaxaca",
  "Tuxtla Gutiérrez",
  "Colima",
  "Tepic",
  "La Paz",
  "Campeche",
  "Tlaxcala",
  "Zacatecas",
  "Durango",
  "Mazatlán",
  "Ensenada",
  "Irapuato",
  "Celaya",
  "Uruapan",
  "Matamoros",
  "Nuevo Laredo",
  "Reynosa",
  "Tampico",
  "Coatzacoalcos",
  "Poza Rica",
  "Pachuca",
  "Xalapa",
  "Tapachula",
  "Puerto Vallarta",
  "Playa del Carmen",
  "Cabo San Lucas",
  "Otra",
];